// <auto-generated />
using System;
using AzureFunc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionsFinal.Data.Migrations
{
    [DbContext(typeof(OlympicsContext))]
    [Migration("20221205184337_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AzureFunc.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Closing")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Opening")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Season")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Athens",
                            Closing = new DateTime(1896, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Greece",
                            Opening = new DateTime(1896, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1896
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            Closing = new DateTime(2000, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(2000, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1900
                        },
                        new
                        {
                            Id = 3,
                            City = "St. Louis",
                            Closing = new DateTime(2004, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1904
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Closing = new DateTime(2008, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "United Kingdom",
                            Opening = new DateTime(2008, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1908
                        },
                        new
                        {
                            Id = 5,
                            City = "Stockholm",
                            Closing = new DateTime(2012, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Sweden",
                            Opening = new DateTime(2012, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1912
                        },
                        new
                        {
                            Id = 6,
                            City = "Antwerp",
                            Closing = new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Belgium",
                            Opening = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1920
                        },
                        new
                        {
                            Id = 7,
                            City = "Chamonix",
                            Closing = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1924
                        },
                        new
                        {
                            Id = 8,
                            City = "Paris",
                            Closing = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1924
                        },
                        new
                        {
                            Id = 9,
                            City = "St. Moritz",
                            Closing = new DateTime(2028, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Switzerland",
                            Opening = new DateTime(2028, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1928
                        },
                        new
                        {
                            Id = 10,
                            City = "Amsterdam",
                            Closing = new DateTime(2028, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Netherlands",
                            Opening = new DateTime(2028, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1928
                        },
                        new
                        {
                            Id = 11,
                            City = "Lake Placid",
                            Closing = new DateTime(1932, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1932, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1932
                        },
                        new
                        {
                            Id = 12,
                            City = "Los Angeles",
                            Closing = new DateTime(1932, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1932, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1932
                        },
                        new
                        {
                            Id = 13,
                            City = "Garmisch-Partenkirchen",
                            Closing = new DateTime(1936, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Germany",
                            Opening = new DateTime(1936, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1936
                        },
                        new
                        {
                            Id = 14,
                            City = "Berlin",
                            Closing = new DateTime(1936, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Germany",
                            Opening = new DateTime(1936, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1936
                        },
                        new
                        {
                            Id = 15,
                            City = "St. Moritz",
                            Closing = new DateTime(1948, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Switzerland",
                            Opening = new DateTime(1948, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1948
                        },
                        new
                        {
                            Id = 16,
                            City = "London",
                            Closing = new DateTime(1948, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "United Kingdom",
                            Opening = new DateTime(1948, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1948
                        },
                        new
                        {
                            Id = 17,
                            City = "Oslo",
                            Closing = new DateTime(1952, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Norway",
                            Opening = new DateTime(1952, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1952
                        },
                        new
                        {
                            Id = 18,
                            City = "Helsinki",
                            Closing = new DateTime(1952, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Finland",
                            Opening = new DateTime(1952, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1952
                        },
                        new
                        {
                            Id = 19,
                            City = "Cortina d'Ampezzo",
                            Closing = new DateTime(1956, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Italy",
                            Opening = new DateTime(1956, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1956
                        },
                        new
                        {
                            Id = 20,
                            City = "Melbourne",
                            Closing = new DateTime(1956, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Oceania",
                            Country = "Australia",
                            Opening = new DateTime(1956, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1956
                        },
                        new
                        {
                            Id = 21,
                            City = "Stockholm",
                            Closing = new DateTime(1956, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Sweden",
                            Opening = new DateTime(1956, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1956
                        },
                        new
                        {
                            Id = 22,
                            City = "Palisades Tahoe",
                            Closing = new DateTime(1960, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1960, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1960
                        },
                        new
                        {
                            Id = 23,
                            City = "Rome",
                            Closing = new DateTime(1960, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Italy",
                            Opening = new DateTime(1960, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1960
                        },
                        new
                        {
                            Id = 24,
                            City = "Innsbruck",
                            Closing = new DateTime(1964, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Austria",
                            Opening = new DateTime(1964, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1964
                        },
                        new
                        {
                            Id = 25,
                            City = "Tokyo",
                            Closing = new DateTime(1964, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "Japan",
                            Opening = new DateTime(1964, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1964
                        },
                        new
                        {
                            Id = 26,
                            City = "Grenoble",
                            Closing = new DateTime(1968, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(1968, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1968
                        },
                        new
                        {
                            Id = 27,
                            City = "Mexico City",
                            Closing = new DateTime(1968, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "Mexico",
                            Opening = new DateTime(1968, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1968
                        },
                        new
                        {
                            Id = 28,
                            City = "Sapporo",
                            Closing = new DateTime(1972, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "Japan",
                            Opening = new DateTime(1972, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1972
                        },
                        new
                        {
                            Id = 29,
                            City = "Munich",
                            Closing = new DateTime(1972, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "West Germany",
                            Opening = new DateTime(1972, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1972
                        },
                        new
                        {
                            Id = 30,
                            City = "Innsbruck",
                            Closing = new DateTime(1976, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Austria",
                            Opening = new DateTime(1976, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1976
                        },
                        new
                        {
                            Id = 31,
                            City = "Montreal",
                            Closing = new DateTime(1976, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "Canada",
                            Opening = new DateTime(1976, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1976
                        },
                        new
                        {
                            Id = 32,
                            City = "Lake Placid",
                            Closing = new DateTime(1980, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1980, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1980
                        },
                        new
                        {
                            Id = 33,
                            City = "Moscow",
                            Closing = new DateTime(1980, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Soviet Union",
                            Opening = new DateTime(1980, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1980
                        },
                        new
                        {
                            Id = 34,
                            City = "Sarajevo",
                            Closing = new DateTime(1984, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Yugoslavia",
                            Opening = new DateTime(1984, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1984
                        },
                        new
                        {
                            Id = 35,
                            City = "Los Angeles",
                            Closing = new DateTime(1984, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1984, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1984
                        },
                        new
                        {
                            Id = 36,
                            City = "Calgary",
                            Closing = new DateTime(1988, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "Canada",
                            Opening = new DateTime(1988, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1988
                        },
                        new
                        {
                            Id = 37,
                            City = "Seoul",
                            Closing = new DateTime(1988, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "South Korea",
                            Opening = new DateTime(1988, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1988
                        },
                        new
                        {
                            Id = 38,
                            City = "Albertville",
                            Closing = new DateTime(1992, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(1992, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1992
                        },
                        new
                        {
                            Id = 39,
                            City = "Barcelona",
                            Closing = new DateTime(1992, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Spain",
                            Opening = new DateTime(1992, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1992
                        },
                        new
                        {
                            Id = 40,
                            City = "Lillehammer",
                            Closing = new DateTime(1994, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Norway",
                            Opening = new DateTime(1994, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1994
                        },
                        new
                        {
                            Id = 41,
                            City = "Atlanta",
                            Closing = new DateTime(1996, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(1996, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 1996
                        },
                        new
                        {
                            Id = 42,
                            City = "Nagano",
                            Closing = new DateTime(1998, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "Japan",
                            Opening = new DateTime(1998, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 1998
                        },
                        new
                        {
                            Id = 43,
                            City = "Sydney",
                            Closing = new DateTime(2000, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Oceania",
                            Country = "Australia",
                            Opening = new DateTime(2000, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2000
                        },
                        new
                        {
                            Id = 44,
                            City = "Salt Lake City",
                            Closing = new DateTime(2002, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(2002, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2002
                        },
                        new
                        {
                            Id = 45,
                            City = "Athens",
                            Closing = new DateTime(2004, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Greece",
                            Opening = new DateTime(2004, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2004
                        },
                        new
                        {
                            Id = 46,
                            City = "Turin",
                            Closing = new DateTime(2006, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Italy",
                            Opening = new DateTime(2006, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2006
                        },
                        new
                        {
                            Id = 47,
                            City = "Beijing",
                            Closing = new DateTime(2008, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "China",
                            Opening = new DateTime(2008, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2008
                        },
                        new
                        {
                            Id = 48,
                            City = "Vancouver",
                            Closing = new DateTime(2010, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "Canada",
                            Opening = new DateTime(2010, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2010
                        },
                        new
                        {
                            Id = 49,
                            City = "London",
                            Closing = new DateTime(2012, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "United Kingdom",
                            Opening = new DateTime(2012, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2012
                        },
                        new
                        {
                            Id = 50,
                            City = "Sochi",
                            Closing = new DateTime(2014, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Russia",
                            Opening = new DateTime(2014, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2014
                        },
                        new
                        {
                            Id = 51,
                            City = "Rio de Janeiro",
                            Closing = new DateTime(2016, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "South America",
                            Country = "Brazil",
                            Opening = new DateTime(2016, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2016
                        },
                        new
                        {
                            Id = 52,
                            City = "Pyeongchang",
                            Closing = new DateTime(2018, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "South Korea",
                            Opening = new DateTime(2018, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2018
                        },
                        new
                        {
                            Id = 53,
                            City = "Tokyo",
                            Closing = new DateTime(2021, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "Japan",
                            Opening = new DateTime(2021, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2020
                        },
                        new
                        {
                            Id = 54,
                            City = "Beijing",
                            Closing = new DateTime(2022, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Asia",
                            Country = "China",
                            Opening = new DateTime(2022, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2022
                        },
                        new
                        {
                            Id = 55,
                            City = "Paris",
                            Closing = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "France",
                            Opening = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2024
                        },
                        new
                        {
                            Id = 56,
                            City = "Milan–Cortina d'Ampezzo",
                            Closing = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Europe",
                            Country = "Italy",
                            Opening = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Winter",
                            Year = 2026
                        },
                        new
                        {
                            Id = 57,
                            City = "Los Angeles",
                            Closing = new DateTime(2028, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "North America",
                            Country = "United States",
                            Opening = new DateTime(2028, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2028
                        },
                        new
                        {
                            Id = 58,
                            City = "Brisbane",
                            Closing = new DateTime(1932, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Continent = "Oceania",
                            Country = "Australia",
                            Opening = new DateTime(1932, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "Summer",
                            Year = 2032
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
